### ISSUE TITLE
Modified Change Password

### ISSUE THREAD

**Issue by tianomagdaong** [pgina/pgina#239] opened 2014-09-10 07:27 UTC
I'm not sure if this is implemented already for the 3.2.4 release but what I wanted to do is to create a generic change password tile wherein it asks the domain\username, then a new tile will appear that will ask for a token that was sent to the user's registered mobile phone or email. Once  the code is entered the user will have a new password.

**Comment by daw42** [comment] 2015-01-08 22:56
Currently, the change password functionality is based on the MS CredentialProvider framework.  In order to modify the fields that appear, you'll need to dig into that code (C++, in `pGina/src/CredentialProvider` ).

**Comment by nate-yocom** [comment] 2016-01-28 19:17
Dupe of #24

**Closed by nate-yocom** 2016-01-28 19:17 UTC
