### ISSUE TITLE
pGina v3.1.8.0 Configuration

### ISSUE THREAD

**Issue by Wotan4New** [pgina/pgina#253] opened 2015-05-29 08:45 UTC
Hi

Is it possible to backup the pGina configuration on a working device so that it can be restored onto multiple devices as part of a automated build process?

Any help would be gratefully received.

Thanks

**Comment by nate-yocom** [comment] 2016-01-28 19:08
Dupe of #207

**Closed by nate-yocom** 2016-01-28 19:08 UTC
